language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - [[ $TRAVIS_PYTHON_VERSION == 2* ]] && pip install -r requirements-py2.txt --use-mirrors
  - [[ $TRAVIS_PYTHON_VERSION == 3* ]] && pip install -r requirements-py3.txt --use-mirrors
  - pip install coveralls
script:
  - python setup.py test
after_success:
  - coveralls
